import { Navbar, SidebarLeft, SidebarRight } from "@components";
import "@styles/globals.css";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Facebook",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#e9ebee] relative">
        <div>
          <Navbar />
          <div className="flex justify-center relative">
            <SidebarLeft />
            {children}
            <SidebarRight />
          </div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
